name: Deploy Project Lodestone App

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: (libLCE) Set up Emscripten
        run: |
          ./deps/libLCE/external/emsdk/emsdk install latest
          ./deps/libLCE/external/emsdk/emsdk activate latest
          source ./deps/libLCE/external/emsdk/emsdk_env.sh

      - name: (libLCE) Configure CMake
        run: >
          cmake -B /home/runner/work/App/App/deps/libLCE/em-build
          -S /home/runner/work/App/App/deps/libLCE/
          -DCMAKE_CXX_COMPILER=em++
          -DCMAKE_C_COMPILER=emcc
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_EXE_LINKER_FLAGS="--bind"
          -DEMSCRIPTEN_DIR="$/home/runner/work/App/App/deps/libLCE/external/emsdk/upstream/emscripten"
          -DCMAKE_TOOLCHAIN_FILE=/home/runner/work/App/App/deps/libLCE/external/emsdk/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake

      - name: (libLCE) Build
        run: >
          cmake --build /home/runner/work/App/App/deps/libLCE/em-build --config Release --target libLCE

      - name: (libLCE) Copy built WASM files
        run: |
          cp /home/runner/work/App/App/deps/libLCE/em-build/*.wasm /home/runner/work/App/App/src/wasm
          cp /home/runner/work/App/App/deps/libLCE/em-build/*.js /home/runner/work/App/App/src/wasm

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: "./dist"

      - name: Deploy to GH Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
